ifeq ($(ANDROID_BUILD_TOP),)
ANDROID_BUILD_TOP := $(srctree)/..
endif

# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm7435-modules/motorola/include
ifneq ($strip($(LINUX_KERNEL_VERSION)),)
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/$(LINUX_KERNEL_VERSION)
endif
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm7435-modules/motorola/drivers/moto_sched

override CONFIG_MOTO_MUTEX_INHERIT := y
override CONFIG_MOTO_RWSEM_INHERIT := y

obj-m += moto_sched.o

ifneq ($(filter m y,$(CONFIG_MOTO_MUTEX_INHERIT)),)
	EXTRA_CFLAGS += -DCONFIG_MOTO_MUTEX_INHERIT
endif

ifneq ($(filter m y,$(CONFIG_MOTO_RWSEM_INHERIT)),)
	EXTRA_CFLAGS += -DCONFIG_MOTO_RWSEM_INHERIT
endif

ifneq ($(filter m y,$(CONFIG_MOTO_FUTEX_INHERIT)),)
	EXTRA_CFLAGS += -DCONFIG_MOTO_FUTEX_INHERIT
endif

ifneq ($(filter m y,$(CONFIG_MOTO_ENABLE_MDPF)),)
	EXTRA_CFLAGS += -DCONFIG_MOTO_ENABLE_MDPF
endif

moto_sched-y := msched_main.o msched_sysfs.o msched_common.o

moto_sched-y += locking/locking_main.o
moto_sched-$(CONFIG_MOTO_MUTEX_INHERIT) += locking/mutex.o
moto_sched-$(CONFIG_MOTO_RWSEM_INHERIT) += locking/rwsem.o
moto_sched-$(CONFIG_MOTO_FUTEX_INHERIT) += locking/futex.o
moto_sched-y += msched_uclamp.o
moto_sched-$(CONFIG_MOTO_ENABLE_MDPF) += mdpf/mdpf_sysfs.o
